version: "3.7"

services:
  app:
    image: node:12-alpine
    command: sh -c "apk add --no-cache python2 g++ make && yarn install && yarn run dev"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: fang0621
      MYSQL_DB: todos
  mysql:
    image: mysql:5.7
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: fang0621
      MYSQL_DATABASE: todos
volumes:
  todo-mysql-data: